package myloe.bean;

import java.util.Date;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table classes
 */
public class Classes {
    /**
     * Database Column Remarks:
     *   班级主键
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column classes.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     * Database Column Remarks:
     *   班级名称
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column classes.name
     *
     * @mbg.generated
     */
    private String name;

    /**
     * Database Column Remarks:
     *   班级创建时间
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column classes.create_dateTime
     *
     * @mbg.generated
     */
    private Date createDatetime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column classes.id
     *
     * @return the value of classes.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column classes.id
     *
     * @param id the value for classes.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column classes.name
     *
     * @return the value of classes.name
     *
     * @mbg.generated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column classes.name
     *
     * @param name the value for classes.name
     *
     * @mbg.generated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column classes.create_dateTime
     *
     * @return the value of classes.create_dateTime
     *
     * @mbg.generated
     */
    public Date getCreateDatetime() {
        return createDatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column classes.create_dateTime
     *
     * @param createDatetime the value for classes.create_dateTime
     *
     * @mbg.generated
     */
    public void setCreateDatetime(Date createDatetime) {
        this.createDatetime = createDatetime;
    }
}